version       = "0.1.0"
author        = "Vexter contributors"
description   = "Viewer and extractor for legacy file formats"
license       = "TBD"
srcDir        = "src"
bin           = @["vexter"]

task gui, "Cross-compile the native Windows GUI":
  exec "nim c --os:windows --cpu:amd64 --gcc.exe:x86_64-w64-mingw32-gcc --gcc.linkerexe:x86_64-w64-mingw32-gcc --app:gui --threads:on --mm:arc --path:src -o:build/vexter-gui.exe src/vexter_gui.nim"

task test, "Run the test suite":
  exec "nim c --path:src -o:build/vexter src/vexter.nim"
  exec "nim c -r --path:src tests/test_amiga_iff_ilbm.nim"
  exec "nim c -r --path:src tests/test_amiga_8svx.nim"
  exec "nim c -r --path:src tests/test_amiga_16sv.nim"
  exec "nim c -r --path:src tests/test_wav.nim"
  exec "nim c -r --path:src tests/test_amiga_acbm.nim"
  exec "nim c -r --path:src tests/test_amiga_anim.nim"
  exec "nim c -r --path:src tests/test_amiga_adf.nim"
  exec "nim c -r --path:src tests/test_amiga_dms.nim"
  exec "nim c -r --path:src tests/test_amiga_workbench_icon.nim"
  exec "nim c -r --path:src tests/test_zip_archive.nim"
  exec "nim c -r --path:src tests/test_pcx.nim"
  exec "nim c -r --path:src tests/test_bmp.nim"
  exec "nim c -r --path:src tests/test_png.nim"
  exec "nim c -r --path:src tests/test_gif.nim"
  exec "nim c -r --path:src tests/test_zx_spectrum_screen.nim"
  exec "nim c -r --path:src tests/test_zx_spectrum_snapshot.nim"
  exec "nim c -r --path:src tests/test_zx_spectrum_basic.nim"
  exec "nim c -r --path:src tests/test_zx_spectrum_tap.nim"
  exec "nim c -r --path:src tests/test_amos_bank.nim"
  exec "nim c -r --path:src tests/test_amos_packed_picture.nim"
  exec "nim c -r --path:src tests/test_amos_bank_set.nim"
  exec "nim c -r --path:src tests/test_amos_program.nim"
  exec "nim c -r --path:src tests/test_amos_sprite_icon_bank.nim"
  exec "nim c -r --path:src tests/test_operations.nim"
  exec "nim c -r --path:src tests/test_cli.nim"
