version       = "0.1.0"
author        = "Peter Spicer and Codex"
description   = "Dependency-free viewer and extractor for reusable file formats"
license       = "BSD-3-Clause"
srcDir        = "src"
bin           = @["vexter"]

task gui, "Cross-compile the native Windows GUI":
  mkDir "build/win32"
  exec "nim c --os:windows --cpu:amd64 --gcc.exe:x86_64-w64-mingw32-gcc --gcc.linkerexe:x86_64-w64-mingw32-gcc --app:gui --threads:on --mm:arc --path:src -o:build/win32/vexter-gui.exe src/vexter_gui.nim"

task cli, "Build the Linux and Windows command-line clients":
  mkDir "build/linux"
  mkDir "build/win32"
  exec "nim c --path:src -o:build/linux/vexter src/vexter.nim"
  exec "nim c --os:windows --cpu:amd64 --gcc.exe:x86_64-w64-mingw32-gcc --gcc.linkerexe:x86_64-w64-mingw32-gcc --path:src -o:build/win32/vexter-cli.exe src/vexter.nim"

task test, "Run the test suite":
  mkDir "build/linux"
  exec "nim c --path:src -o:build/linux/vexter src/vexter.nim"
  exec "nim c -r --path:src tests/test_amiga_iff_ilbm.nim"
  exec "nim c -r --path:src tests/test_amiga_8svx.nim"
  exec "nim c -r --path:src tests/test_amiga_16sv.nim"
  exec "nim c -r --path:src tests/test_wav.nim"
  exec "nim c -r --path:src tests/test_amiga_acbm.nim"
  exec "nim c -r --path:src tests/test_amiga_pbm.nim"
  exec "nim c -r --path:src tests/test_amiga_anim.nim"
  exec "nim c -r --path:src tests/test_amiga_adf.nim"
  exec "nim c -r --path:src tests/test_amiga_dms.nim"
  exec "nim c -r --path:src tests/test_xpk_shri.nim"
  exec "nim c -r --path:src tests/test_powerpacker.nim"
  exec "nim c -r --path:src tests/test_amiga_workbench_icon.nim"
  exec "nim c -r --path:src tests/test_zip_archive.nim"
  exec "nim c -r --path:src tests/test_iso9660.nim"
  exec "nim c -r --path:src tests/test_lha_archive.nim"
  exec "nim c -r --path:src tests/test_amiga_hunk.nim"
  exec "nim c -r --path:src tests/test_pcx.nim"
  exec "nim c -r --path:src tests/test_bmp.nim"
  exec "nim c -r --path:src tests/test_windows_icon.nim"
  exec "nim c -r --path:src tests/test_bitmap_font.nim"
  exec "nim c -r --path:src tests/test_fzx.nim"
  exec "nim c -r --path:src tests/test_png.nim"
  exec "nim c -r --path:src tests/test_jpeg.nim"
  exec "nim c -r --path:src tests/test_gif.nim"
  exec "nim c -r --path:src tests/test_qoi.nim"
  exec "nim c -r --path:src tests/test_netpbm.nim"
  exec "nim c -r --path:src tests/test_tga.nim"
  exec "nim c -r --path:src tests/test_flic.nim"
  exec "nim c -r --path:src tests/test_ansi_art.nim"
  exec "nim c -r --path:src tests/test_zx_spectrum_screen.nim"
  exec "nim c -r --path:src tests/test_zx_spectrum_snapshot.nim"
  exec "nim c -r --path:src tests/test_zx_spectrum_basic.nim"
  exec "nim c -r --path:src tests/test_zx_spectrum_tap.nim"
  exec "nim c -r --path:src tests/test_amos_bank.nim"
  exec "nim c -r --path:src tests/test_amos_packed_picture.nim"
  exec "nim c -r --path:src tests/test_amos_bank_set.nim"
  exec "nim c -r --path:src tests/test_amos_program.nim"
  exec "nim c -r --path:src tests/test_amos_sprite_icon_bank.nim"
  exec "nim c -r --path:src tests/test_operations.nim"
  exec "nim c -r --path:src tests/test_format_refinement.nim"
  exec "nim c -r --path:src tests/test_openraster.nim"
  exec "nim c -r --path:src -d:VexterCliPath=build/linux/vexter tests/test_cli.nim"
